name: build

on:
  push:
    tags:
      - '**'
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push tag
        uses: docker/build-push-action@v3
        if: startsWith(github.event.ref, 'refs/tags/v')
        with:
          context: .
          push: true
          tags: "ghcr.io/${{ github.repository }}:${{ github.ref_name }}"

      - name: Build and push latest tag
        uses: docker/build-push-action@v3
        if: startsWith(github.event.ref, 'refs/tags/v') != true
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
